import type { Metadata, Viewport } from 'next';
import { Poppins } from 'next/font/google';
import Header from './components/header/header';

import './globals.css';
import { MenusDesk } from './components/menuDesk/menu';

const poppins = Poppins({
    weight: ['400', '600'], // você pode especificar os pesos que deseja usar
    subsets: ['latin'],
});

export const viewport: Viewport = {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
};

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br">
            <body className={poppins.className}>
                {/*     <Theme> */}

                <Header />
                <div className="flex w-full ">
                    <div className="h-screen w-[350px] hidden md:block border-2 rounded-r-2xl shadow-2xl">
                        <MenusDesk />
                    </div>
                    <div className="p-5 lg:py-10 bg-[#FAFAFA]  lg:container lg:gap-7  lg:mx-auto lg:min-h-[100%] w-full">{children}</div>
                </div>

                {/*    </Theme> */}
            </body>
        </html>
    );
}
