import type { Metadata, Viewport } from "next";
import { Poppins } from "next/font/google";
import Header from "./components/header/header";
/* import "@radix-ui/themes/styles.css"; */
import "./globals.css";
/* import { Theme } from "@radix-ui/themes"; */

const poppins = Poppins({
  weight: ["400", "600"], // você pode especificar os pesos que deseja usar
  subsets: ["latin"],
});

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={poppins.className}>
        {/*     <Theme> */}
        <Header />
        <div className="p-5">{children}</div>
        {/*    </Theme> */}
      </body>
    </html>
  );
}
